ARG  BUILD_TAG
FROM ghcr.io/ibm-samsung-aisystem/dc:${BUILD_TAG}

ARG DEE_COMMIT_ID=""
ARG DEEPTOOLS_COMMIT_ID=""
ARG SENDNN_COMMIT_ID=""
ARG PYTORCH_COMMIT_ID=""
ARG DEE_COMMIT_REPO=""
ARG DEEPTOOLS_COMMIT_REPO=""
ARG SENDNN_COMMIT_REPO=""
ARG PYTORCH_COMMIT_REPO=""

LABEL DEE_COMMIT_ID=${DEE_COMMIT_ID} \
    DEEPTOOLS_COMMIT_ID=${DEEPTOOLS_COMMIT_ID} \
    SENDNN_COMMIT_ID=${SENDNN_COMMIT_ID} \
    PYTORCH_COMMIT_ID=${PYTORCH_COMMIT_ID} \
    DEE_COMMIT_REPO=${DEE_COMMIT_REPO}  \
    DEEPTOOLS_COMMIT_REPO=${DEEPTOOLS_COMMIT_REPO} \
    SENDNN_COMMIT_REPO=${SENDNN_COMMIT_REPO} \
    PYTORCH_COMMIT_REPO=${PYTORCH_COMMIT_REPO}

USER root

ENV DEE_COMMIT_ID=${DEE_COMMIT_ID} \
    DEEPTOOLS_COMMIT_ID=${DEEPTOOLS_COMMIT_ID} \
    SENDNN_COMMIT_ID=${SENDNN_COMMIT_ID} \
    PYTORCH_COMMIT_ID=${PYTORCH_COMMIT_ID} \
    DEE_COMMIT_REPO=${DEE_COMMIT_REPO}  \
    DEEPTOOLS_COMMIT_REPO=${DEEPTOOLS_COMMIT_REPO} \
    SENDNN_COMMIT_REPO=${SENDNN_COMMIT_REPO} \
    PYTORCH_COMMIT_REPO=${PYTORCH_COMMIT_REPO} \
    PYTHON_VERSION=3.8 \
    PATH=$HOME/.local/bin/:$PATH \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    PIP_NO_CACHE_DIR=off

ENV BASH_ENV="/opt/anaconda/bin/activate ${APP_ROOT}" \
    ENV="/opt/anaconda/bin/activate ${APP_ROOT}" \
    PROMPT_COMMAND=". /opt/anaconda/bin/activate ${APP_ROOT}"


ENV SUMMARY="Pytorch container" \
    DESCRIPTION=""

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Anaconda Python 3.8" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,python,python38,python-38,anaconda-python38" \
      com.redhat.component="python-38-container" \
      name="ubi8/ai-toolchain-pytorch" \
      version="1" \
      usage="" \
      maintainer="Subin Modeel <smodeel@redhat.com>"

#using podman -v
#COPY ./pytorch ${APP_ROOT}/pytorch/

ENV SENDNN_DIR=${APP_ROOT}/sendnn_dir/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${SENDNN_DIR}/lib \
    PATH=$PATH:${SENDNN_DIR}/bin \
    DEEPTOOLS_PATH=$SENDNN_DIR/share \
    SENCORES=1

RUN ls -lah ${APP_ROOT} && \
    ls -lah ${APP_ROOT}/sendnn_dir/ && \
    ls -lah ${APP_ROOT}/src/pytorch/ && \
    cd ${APP_ROOT}/src/pytorch/ && \
    python setup.py clean && \
    python setup.py install
RUN cd ${APP_ROOT}/src/pytorch/sen && \
    python setup.py clean && \
    python setup.py install

#RUN chown -R 1001:0 ${APP_ROOT} && \
#    fix-permissions ${APP_ROOT} -P && \
#    fix-permissions /opt/anaconda -P && \
#    rpm-file-permissions

USER 1001

# Set the default CMD to print the usage of the language image.
CMD $STI_SCRIPTS_PATH/usage
